---
- name: Install software applications
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: no
  tasks:
   - name: Install/UnInstall
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
         




...
